// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type chainscopeProcInfo struct {
	Ppid     uint32
	RootPid  uint32
	Phase    uint8
	Comm     [16]int8
	RootComm [16]int8
	_        [3]byte
}

// loadChainscope returns the embedded CollectionSpec for chainscope.
func loadChainscope() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ChainscopeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load chainscope: %w", err)
	}

	return spec, err
}

// loadChainscopeObjects loads chainscope and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*chainscopeObjects
//	*chainscopePrograms
//	*chainscopeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
//
// When obj is *chainscopeObjects and the compiled BPF object predates the
// drop_count map (i.e. make generate hasn't been run yet), DropCount is set
// to nil and all other maps/programs are loaded normally.
func loadChainscopeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadChainscope()
	if err != nil {
		return err
	}

	// Backward-compatible load: if the compiled object doesn't have drop_count
	// (older .o file), fall back to loading without it and leave DropCount nil.
	if co, ok := obj.(*chainscopeObjects); ok {
		if _, hasDropCount := spec.Maps["drop_count"]; !hasDropCount {
			type legacyMaps struct {
				EnvScratch *ebpf.Map `ebpf:"env_scratch"`
				Events     *ebpf.Map `ebpf:"events"`
				ProcTree   *ebpf.Map `ebpf:"proc_tree"`
				SavedExecs *ebpf.Map `ebpf:"saved_execs"`
			}
			type legacyObjects struct {
				chainscopePrograms
				legacyMaps
			}
			var legacy legacyObjects
			if err := spec.LoadAndAssign(&legacy, opts); err != nil {
				return err
			}
			co.chainscopePrograms = legacy.chainscopePrograms
			co.EnvScratch         = legacy.legacyMaps.EnvScratch
			co.Events             = legacy.legacyMaps.Events
			co.ProcTree           = legacy.legacyMaps.ProcTree
			co.SavedExecs         = legacy.legacyMaps.SavedExecs
			co.DropCount          = nil
			return nil
		}
	}

	return spec.LoadAndAssign(obj, opts)
}

// chainscopeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type chainscopeSpecs struct {
	chainscopeProgramSpecs
	chainscopeMapSpecs
}

// chainscopeSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type chainscopeProgramSpecs struct {
	TraceBpf         *ebpf.ProgramSpec `ebpf:"trace_bpf"`
	TraceConnect     *ebpf.ProgramSpec `ebpf:"trace_connect"`
	TraceExecve      *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceExecveExit  *ebpf.ProgramSpec `ebpf:"trace_execve_exit"`
	TraceExecveat    *ebpf.ProgramSpec `ebpf:"trace_execveat"`
	TraceExit        *ebpf.ProgramSpec `ebpf:"trace_exit"`
	TraceFchmodat    *ebpf.ProgramSpec `ebpf:"trace_fchmodat"`
	TraceGetaddrinfo *ebpf.ProgramSpec `ebpf:"trace_getaddrinfo"`
	TraceMemfdCreate *ebpf.ProgramSpec `ebpf:"trace_memfd_create"`
	TraceOpenat      *ebpf.ProgramSpec `ebpf:"trace_openat"`
}

// chainscopeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type chainscopeMapSpecs struct {
	DropCount  *ebpf.MapSpec `ebpf:"drop_count"`
	EnvScratch *ebpf.MapSpec `ebpf:"env_scratch"`
	Events     *ebpf.MapSpec `ebpf:"events"`
	ProcTree   *ebpf.MapSpec `ebpf:"proc_tree"`
	SavedExecs *ebpf.MapSpec `ebpf:"saved_execs"`
}

// chainscopeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadChainscopeObjects or ebpf.CollectionSpec.LoadAndAssign.
type chainscopeObjects struct {
	chainscopePrograms
	chainscopeMaps
}

func (o *chainscopeObjects) Close() error {
	return _ChainscopeClose(
		&o.chainscopePrograms,
		&o.chainscopeMaps,
	)
}

// chainscopeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadChainscopeObjects or ebpf.CollectionSpec.LoadAndAssign.
// DropCount is nil when running against a pre-drop-counter compiled object
// (i.e. before `make generate` was run after the drop_count map was added).
type chainscopeMaps struct {
	DropCount  *ebpf.Map `ebpf:"drop_count"`
	EnvScratch *ebpf.Map `ebpf:"env_scratch"`
	Events     *ebpf.Map `ebpf:"events"`
	ProcTree   *ebpf.Map `ebpf:"proc_tree"`
	SavedExecs *ebpf.Map `ebpf:"saved_execs"`
}

func (m *chainscopeMaps) Close() error {
	// DropCount may be nil on older compiled objects — (*ebpf.Map).Close() is nil-safe.
	return _ChainscopeClose(
		m.DropCount,
		m.EnvScratch,
		m.Events,
		m.ProcTree,
		m.SavedExecs,
	)
}

// chainscopePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadChainscopeObjects or ebpf.CollectionSpec.LoadAndAssign.
type chainscopePrograms struct {
	TraceBpf         *ebpf.Program `ebpf:"trace_bpf"`
	TraceConnect     *ebpf.Program `ebpf:"trace_connect"`
	TraceExecve      *ebpf.Program `ebpf:"trace_execve"`
	TraceExecveExit  *ebpf.Program `ebpf:"trace_execve_exit"`
	TraceExecveat    *ebpf.Program `ebpf:"trace_execveat"`
	TraceExit        *ebpf.Program `ebpf:"trace_exit"`
	TraceFchmodat    *ebpf.Program `ebpf:"trace_fchmodat"`
	TraceGetaddrinfo *ebpf.Program `ebpf:"trace_getaddrinfo"`
	TraceMemfdCreate *ebpf.Program `ebpf:"trace_memfd_create"`
	TraceOpenat      *ebpf.Program `ebpf:"trace_openat"`
}

func (p *chainscopePrograms) Close() error {
	return _ChainscopeClose(
		p.TraceBpf,
		p.TraceConnect,
		p.TraceExecve,
		p.TraceExecveExit,
		p.TraceExecveat,
		p.TraceExit,
		p.TraceFchmodat,
		p.TraceGetaddrinfo,
		p.TraceMemfdCreate,
		p.TraceOpenat,
	)
}

func _ChainscopeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed chainscope_x86_bpfel.o
var _ChainscopeBytes []byte
