// Package loader loads the chainscope eBPF programs and reads events from the
// ring buffer. The BPF objects struct is generated by `go generate` (see gen.go).
package loader

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"

	"github.com/chainscope/chainscope/internal/types"
)

// Loader holds the loaded BPF objects and attached tracepoints/uprobes.
type Loader struct {
	objs  chainscopeObjects
	links []link.Link
	rd    *ringbuf.Reader
}

// New loads the compiled eBPF object into the kernel and attaches all hooks.
// Caller must call Close() when done.
func New() (*Loader, error) {
	if err := rlimit.RemoveMemlock(); err != nil {
		return nil, fmt.Errorf("removing memlock: %w", err)
	}

	var objs chainscopeObjects
	if err := loadChainscopeObjects(&objs, nil); err != nil {
		return nil, fmt.Errorf("loading BPF objects: %w", err)
	}

	l := &Loader{objs: objs}

	mandatory := []struct {
		group   string
		name    string
		program *ebpf.Program
	}{
		{"syscalls", "sys_enter_execve",       objs.TraceExecve},
		{"syscalls", "sys_exit_execve",        objs.TraceExecveExit},
		{"sched",    "sched_process_exit",     objs.TraceExit},
		{"syscalls", "sys_enter_openat",       objs.TraceOpenat},
		{"syscalls", "sys_enter_connect",      objs.TraceConnect},
		{"syscalls", "sys_enter_memfd_create", objs.TraceMemfdCreate},
		{"syscalls", "sys_enter_execveat",     objs.TraceExecveat},
		{"syscalls", "sys_enter_fchmodat",     objs.TraceFchmodat},
	}
	for _, h := range mandatory {
		lnk, err := link.Tracepoint(h.group, h.name, h.program, nil)
		if err != nil {
			l.Close()
			return nil, fmt.Errorf("attaching %s/%s: %w", h.group, h.name, err)
		}
		l.links = append(l.links, lnk)
	}

	// sys_enter_bpf may not exist on all kernel configs — optional.
	if lnk, err := link.Tracepoint("syscalls", "sys_enter_bpf", objs.TraceBpf, nil); err != nil {
		log.Printf("BPF self-load detection disabled: %v", err)
	} else {
		l.links = append(l.links, lnk)
	}

	// DNS getaddrinfo uprobe in libc — optional.
	if libcPath, err := findLibc(); err != nil {
		log.Printf("DNS uprobe disabled: %v", err)
	} else if ex, err := link.OpenExecutable(libcPath); err != nil {
		log.Printf("DNS uprobe disabled: could not open %s: %v", libcPath, err)
	} else if ulnk, err := ex.Uprobe("getaddrinfo", objs.TraceGetaddrinfo, nil); err != nil {
		log.Printf("DNS uprobe disabled: %v", err)
	} else {
		l.links = append(l.links, ulnk)
	}

	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		l.Close()
		return nil, fmt.Errorf("opening ring buffer: %w", err)
	}
	l.rd = rd

	return l, nil
}

// ReadEvent blocks until an event is available, decodes and returns it.
// Returns (nil, nil) on EOF (loader closed).
func (l *Loader) ReadEvent() (*types.ChainEvent, error) {
	record, err := l.rd.Read()
	if err != nil {
		if errors.Is(err, ringbuf.ErrClosed) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading ring buffer: %w", err)
	}

	var evt types.ChainEvent
	if err := binary.Read(bytes.NewReader(record.RawSample), binary.LittleEndian, &evt); err != nil {
		return nil, fmt.Errorf("decoding event: %w", err)
	}
	return &evt, nil
}

// SeedPID inserts pid into the BPF proc_tree as a root node so that CI mode
// can track a command started before the loader attached.
func (l *Loader) SeedPID(pid uint32, comm string) error {
	var info chainscopeProcInfo
	info.RootPid = pid
	b := []byte(comm)
	if len(b) > 15 {
		b = b[:15]
	}
	for i, c := range b {
		info.Comm[i] = int8(c)
		info.RootComm[i] = int8(c)
	}
	return l.objs.ProcTree.Put(&pid, &info)
}

// DroppedEvents returns the cumulative count of events dropped because the
// ring buffer was full at the time of the BPF program's reserve call.
// Returns 0 if the loaded BPF object predates drop_count support (run
// `make generate && make build` to enable accurate drop tracking).
func (l *Loader) DroppedEvents() uint64 {
	if l.objs.DropCount == nil {
		return 0
	}
	var key uint32
	var val uint64
	if err := l.objs.DropCount.Lookup(&key, &val); err != nil {
		return 0
	}
	return val
}

// Close detaches all hooks and frees BPF objects.
func (l *Loader) Close() {
	if l.rd != nil {
		l.rd.Close()
	}
	for _, lnk := range l.links {
		lnk.Close()
	}
	l.objs.Close()
}

// findLibc returns the path to the system libc shared library.
func findLibc() (string, error) {
	if path, err := libcFromMaps(); err == nil {
		return path, nil
	}
	candidates := []string{
		"/lib/x86_64-linux-gnu/libc.so.6",
		"/lib/aarch64-linux-gnu/libc.so.6",
		"/lib/arm-linux-gnueabihf/libc.so.6",
		"/lib/i386-linux-gnu/libc.so.6",
		"/usr/lib/x86_64-linux-gnu/libc.so.6",
		"/usr/lib/libc.so.6",
		"/lib/libc.so.6",
		"/usr/lib64/libc.so.6",
		"/lib64/libc.so.6",
	}
	for _, p := range candidates {
		if _, err := os.Stat(p); err == nil {
			return p, nil
		}
	}
	return "", fmt.Errorf("libc.so.6 not found in known paths")
}

// libcFromMaps reads /proc/self/maps to find the loaded libc path.
func libcFromMaps() (string, error) {
	data, err := os.ReadFile("/proc/self/maps")
	if err != nil {
		return "", err
	}
	for _, line := range bytes.Split(data, []byte("\n")) {
		if bytes.Contains(line, []byte("libc")) && bytes.Contains(line, []byte(".so")) {
			fields := bytes.Fields(line)
			if len(fields) >= 6 {
				p := string(fields[5])
				if len(p) > 0 && p[0] == '/' {
					if _, err := os.Stat(p); err == nil {
						return filepath.Clean(p), nil
					}
				}
			}
		}
	}
	return "", fmt.Errorf("not found in /proc/self/maps")
}
